### ISSUE TITLE
Can't use project type 'file'

### ISSUE THREAD

**Issue by wilsonpinto** [zanata/repo-sync#1]
I am trying to sync html files with github repo for sync to zanata project, but it seems isn't working for any kind of files of the project type 'file'. 

Output
```
     [java] [!] Using EXPERIMENTAL project type 'file'.
     [java] [INFO] no valid types specified; nothing to do
```

Html it's important to me since i need to have a nice clean html output.

**Note**: Changing only project type to Gettext works perfectly with .pot files.

**Comment by carlosmunoz** [comment]
@wilsonpinto If you are interested in the sync functionality, you might want to have a look at the Zanata jenkins plugin (https://wiki.jenkins-ci.org/display/JENKINS/Zanata+Plugin) which is a better way of doing what this (unsupported) script does.
With regards to the message you are seeing, there is a command line argument to the push (`--file-types`) which specifies which file types it will process. You can look at the client's help command for more info.

**Comment by wilsonpinto** [comment]
thanks, @carlosmunoz by adding `--file-types html` flag to options_push fixed it.
